[versions]
kotlin = "2.1.20"
fabric-loom = "1.10-SNAPSHOT"
iridium = "3.4.0"
# Dependencies
lithostitched = "1ifn2416" # 1.2.6 | swhich to 1.4.8-fabric-1.21 |
fzzy-config = "0.6.9+1.21"

# QoL
modmenu = "11.0.3"
emi = "1.1.22+1.21.1"
# Testing
creative-works = "0.4.0"

[libraries]
# Dependencies
lithostitched = { module = "maven.modrinth:lithostitched", version.ref = "lithostitched" }
fzzy-config = { module = "me.fzzyhmstrs:fzzy_config", version.ref = "fzzy-config" }
# QoL
modmenu = { module = "com.terraformersmc:modmenu", version.ref = "modmenu" }
emi = { module = "dev.emi:emi-fabric", version.ref = "emi" }
# Testing
creative-works = { module = "org.teamvoided:creative_works", version.ref = "creative-works" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
fabric-loom = { id = "fabric-loom", version.ref = "fabric-loom" }
iridium = { id = "org.teamvoided.iridium", version.ref = "iridium"}
iridium-publish = { id = "iridium.project.publish-script", version.ref = "iridium"}
iridium-upload = { id = "iridium.mod.upload-script", version.ref = "iridium" }
